services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: network-toolkit-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - BACKEND_URL=http://localhost:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s